import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";
import MobileFooter from "@/components/MobileFooter";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const vazirMatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["latin", "arabic"],  // You can specify 'latin' and 'arabic' subsets if you need
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={`${geistSans.variable} ${geistMono.variable} ${vazirMatn.className} antialiased bg-[#f2f0fd] `}>
  {/* Toaster must go here */}
  <Toaster
    position="top-right"
    toastOptions={{
      duration: 4000,
      style: {
        zIndex: 9999,
        background: '#333',
        color: '#fff',
      },
    }}
  />

  {/* Desktop View */}
  <div className="hidden lg:flex h-screen overflow-hidden">
    <div className="w-64 fixed h-screen p-4">
      <Sidebar />
    </div>

    <div className="flex-1 ml-64 flex items-center justify-center p-4">
      <div className="rounded-2xl w-full h-full overflow-hidden flex flex-col shadow-md drop-shadow-md">
        <div className="flex-1 overflow-y-auto">
          <div className="sticky top-0 rounded-2xl">
            <Header />
          </div>
          <div>
            {children}
          </div>
        </div>
      </div>
    </div>
  </div>

  {/* Mobile View */}
  <div className="lg:hidden">
    <Header />
    {children}
  </div>

  <MobileFooter />
</body>



    </html>
  );
}

// <div className="flex h-full overflow-hidden">
// Sidebar - hidden on mobile
// <div className="hidden lg:block">
//   <Sidebar />
// </div>

// <div className="flex flex-col flex-1">
//   Header - always visible

//   <div className="flex-1  lg:pt-4 lg:px-4">
//     Rounded container - only on desktop
//     <div className="lg:rounded-t-2xl    drop-shadow-xl  shadow-xl  h-full lg:bg-white    ">
//   <div className="fixed w-full h-7 bg-black top-[10px] left-0">

//   </div>
//       {children}
//     </div>
//   </div>
// </div>
// </div>
//!...........................
{/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
  Desktop View
  <div className="hidden lg:flex h-screen overflow-hidden">
    Sidebar - fixed
    <div className="w-64 fixed h-screen p-4">
      <Sidebar />
    </div>

    Right side: padded, scrollable inside, with fixed height
    <div className="flex-1 ml-64 flex items-center justify-center p-4 ">
      <div className=" rounded-xl w-full h-full overflow-hidden flex flex-col shadow-md drop-shadow-md">
        Scrollable inner area
        <div className="flex-1 overflow-y-auto">
          Sticky header
          <div className="sticky top-0 z-10  rounded-t-xl">
            <Header />
          </div>
          Content
          <div className="">
            {children}
          </div>
        </div>
      </div>
    </div>
  </div>

  Mobile View
  <div className="lg:hidden">
    <Header />
    {children}
  </div>

  Mobile Footer
  <MobileFooter />
</body> */}